# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20170322_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bidlist',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_bidlist_+', to='rango.Page'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ownlist',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_ownlist_+', to='rango.Page'),
        ),
    ]
