# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20170321_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='closingtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 18, 17, 0, 400000, tzinfo=utc)),
        ),
    ]
