# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20170321_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='closingtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
